[package]
authors = ["Sean Leffler <sean@errno.com>"]
name = "ffi-pool"
version = "0.1.0"

description = "Object pool types useful for FFI code."

license = "MPL-2.0"

[dependencies]
memchr = "1.0.1"
objpool = "0.2.0"
take_mut = "0.2.0"

[dev-dependencies]
lazy_static = "0.2.8"
